FROM node:5.9.0
MAINTAINER Robert Achleitner <achleitner@redlever.solutions>

RUN apt-get update && \
    apt-get install -y inotify-tools unzip && \
    wget https://github.com/Yelp/dumb-init/releases/download/v1.0.1/dumb-init_1.0.1_amd64.deb && \
    dpkg -i dumb-init_*.deb

ADD app/ /opt/www/app
ADD src-www/ /opt/www/src

RUN mkdir /opt/www/tmp-script && cd /opt/www/app && npm install --production
ADD start-node-prod.sh /opt/www

CMD ["dumb-init" , "/opt/www/start-node-prod.sh"]
