FROM node:5.9.0

MAINTAINER achleitner@redlever.solutions

RUN apt-get update && apt-get install inotify-tools unzip -y && wget https://github.com/Yelp/dumb-init/releases/download/v1.0.1/dumb-init_1.0.1_amd64.deb && dpkg -i dumb-init_*.deb

ADD app /opt/www/app

RUN mkdir /opt/www/tmp-script && cd /opt/www/app && npm install && npm install -g nodemon

ADD start-node-dev.sh /opt/www

ADD watch-tmp-script.sh /opt/www

ADD watch-app-src.sh /opt/www


CMD ["dumb-init" , "/opt/www/start-node-dev.sh"]



